### ISSUE TITLE
Generate files from another package

### ISSUE THREAD

**Issue by jpearll** [ServiceWeaver/weaver#224] opened 2023-04-05 14:45 UTC
Hi, I am pretty new to this project but found it very interesting!

I am working on building a hexagonal architecture structure in Go, and one of the thing I am doing is separating the ports (interface) from their corresponding concrete implementations adapters.

I was looking to compose my adapter with the weaver.Implements[T], where T is the port (interface, abstraction) which reside on another package.

There is this limitation now, of requiring the interface in the same package as the concrete implementation (when using the weaver CLI). For me that goes against the coupling and segregation concerns I want to enforce with this type of architecture. 

I was wondering if that limitation be removed in the future.

Thanks

**Comment by mwhittaker** [comment] 2023-04-05 16:07
Hi @jpearll! Thanks so much for checking out the project. You're totally correct that right now we require a component interface and component implementation to be in the same package. We elaborate on this more in #98. I'll close this issue as a duplicate of #98, if that's okay with you. We'll definitely re-examine the limitation and see if it can be removed. Feel free to re-open if you have any other questions :)

**Closed by mwhittaker** 2023-04-05 16:07 UTC
