### ISSUE TITLE
multi deploy: not supported by windows

### ISSUE THREAD

**Issue by lemon-1997** [ServiceWeaver/weaver#127] opened 2023-03-07 12:34 UTC
when I executed `weaver multi deploy weaver.toml`, it doesn't work.
config
```
[serviceweaver]
name = "weaver"
binary = "./weaver.exe"
```
temp/serviceweaver/logs/weaver-multiweaver..f1de7a14-6cfb-49fb-9f63-1fec84875a3b.error.log
```
,  
weaver
babysitter"$f1de7a14-6cfb-49fb-9f63-1fec84875a3b)#9N? 2error:dC:/Users/lemon/go/pkg/mod/github.com/!service!weaver/weaver@v0.1.1/internal/babysitter/babysitter.go@?Je.RunRserviceweaver/systemR RerrRSfork/exec C:\Users\lemon\GolandProjects\weaver\weaver.exe: not supported by windows,  
weaver
babysitter"$f1de7a14-6cfb-49fb-9f63-1fec84875a3b)#9N? 2error:dC:/Users/lemon/go/pkg/mod/github.com/!service!weaver/weaver@v0.1.1/internal/babysitter/babysitter.go@?Je.RunRserviceweaver/systemR RerrRSfork/exec C:\Users\lemon\GolandProjects\weaver\weaver.exe: not supported by windows
```

is weaver multiprocess does not support windows?

**Comment by charles-chenzz** [comment] 2023-03-08 02:09
it's a bug and the team fixing it I guess. In the mean time you can change the name and delete files on ``/tmp/serviceweaver/logs/weaver-multi`` to try again to see if it help

**Comment by lemon-1997** [comment] 2023-03-08 02:57
> it's a bug and the team fixing it I guess. In the mean time you can change the name and delete files on `/tmp/serviceweaver/logs/weaver-multi` to try again to see if it help

delete files doesn't work. i think  the problem is ExtraFiles is not supported on Windows.
```go
// ExtraFiles specifies additional open files to be inherited by the
// new process. It does not include standard input, standard output, or
// standard error. If non-nil, entry i becomes file descriptor 3+i.
//
// ExtraFiles is not supported on Windows.
ExtraFiles []*[os](https://pkg.go.dev/os).[File](https://pkg.go.dev/os#File)
```

**Comment by rgrandl** [comment] 2023-03-10 18:09
Duplicate of #81

**Closed** 2023-03-21 11:15 UTC
